FROM --platform=linux/amd64 regentmarkets/debian-perl:bullseye-5.26.2

WORKDIR /app
COPY cpanfile-deadlock .

RUN cpanm --cpanfile cpanfile-deadlock --installdeps .

COPY test2.pl .

ENTRYPOINT [ "perl", "/app/test2.pl"]
