version: '3'
services:
  perl-script:
    build:
      context: .
      dockerfile: Dockerfile-deadlock
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
