FROM --platform=linux/amd64 regentmarkets/debian-perl:bullseye-5.26.2

WORKDIR /app
COPY cpanfile .

RUN cpanm -n --cpanfile cpanfile-memory --installdeps .

COPY test1.pl .

ENTRYPOINT [ "perl", "/app/test1.pl"]
